<?php 
function length_array($array) {
	if (is_array($array)) {
		$n=0;
		foreach ($array as $value) {
			$n++;
		}
		return $n;
	}
	else return '0';
}
$form=new Form_Alliance();
$form->setAction($this->url(array('action'=>'create')))
	->getElement('server')->setValue(Model_User::getInstance()->server->selected);
$members="<ol>";
foreach ($this->ally->members as $value) {
	$members.='<li class="'.$value['role'].'">'.$value['username']."</li>";
}
$members.="</ol>";
$this->key=array('{ally_name}'=>$this->ally->data['name'],
		'{name}'=>$this->t->_('NAME'),
		'{description}'=>$this->t->_('DESCRIPTION2'),
		'{ally_desc}'=>$this->ally->data['description'],
		'{member}'=>$this->t->_('MEMBER'),
		'{num}'=>length_array($this->ally->members),
		'{table}'=>$form->render(),
		'{LIST}'=>$members
);
if ($this->pending) {
	echo '<center>Sei in attesa che l\'ally {ally_name} ti accetti<br />
puoi ritirare la richiesta cliccando <a href="'.$this->url(array('action'=>'leave','aid'=>$this->ally->data['id'])).'" >qui</a>
</center>';
}
elseif ($this->ally) {// descrizione ally visibile solo agli alleati

?>

	<table class="ally" >
		<tr>
			<td><b>{name}</b> : {ally_name}
				<div><b>{member}</b> : {num}</div>
			</td>
			<td><b>{member}</b></td>
		</tr>
		<tr>
			<td><b>{description}</b></td>
			<td rowspan="2"><div style="min-height: 200px;text-align: left;">{LIST}</div></td>
			</tr>
		<tr>
			<td><div style="text-align: right;"><button class="edit">[EDIT]</button></div>
			<div class="ally"><div>{ally_desc}</div><textarea cols="28" rows="15" class="ally">{ally_desc}</textarea></div>
			</td>
		</tr>
<!-- lista utenti -->
</table>



<?php /* @todo ri implementare mappa
<a href="map.php?ally=".$ally."&resize=1&g=1" rel="thumbnail" title="mappa">
<img class="image" width="200" height="200" src="map.php?ally=".$ally."&resize=1&g=1" title="G1" /></a>

<a href="map.php?ally=".$ally."&resize=1&g=2" rel="thumbnail" title="mappa">
<img class="image" width="200" height="200" src="map.php?ally=".$ally."&resize=1&g=2" title="G2" /></a>

<a href="map.php?ally=".$ally."&resize=1&g=3" rel="thumbnail" title="mappa">
<img class="image" width="200" height="200" src="map.php?ally=".$ally."&resize=1&g=3" title="G3" /></a>

$pianeti=$Db->totable("SELECT `us_pianeti`.* , `us_player`.`nome` FROM `us_pianeti` , `us_player` WHERE `alleanza`='".$ally."' AND `nome`=`us_pianeti`.`id`");
$maxx=0;$maxy=0;$i=0;$minx=0;$miny=0;
while($pianeti[$i])
{
	$minx= $pianeti[$i]['x'] < $minx ? $pianeti[$i]['x'] : $minx ;
	$miny= $pianeti[$i]['y'] < $miny ? $pianeti[$i]['y'] : $miny ;
	$maxx= $pianeti[$i]['x'] > $maxx ? $pianeti[$i]['x'] : $maxx ;
	$maxy= $pianeti[$i]['y'] > $maxy ? $pianeti[$i]['y'] : $maxy ;
	$i++;
}
$max=$maxx > $maxy ? $maxx : $maxy;
$min=$minx < $miny ? $minx : $miny;
$min=0-$min;
$max=$max > $min ? $max : $min ;
$max++;
$gr=intval(400/$max);
echo "<map name="map" id="map">";
for($i=0;$pianeti[$i];$i++)
{
$x=intval($pianeti[$i]['x']*400/$max);
$off=intval(400);
$y=intval($pianeti[$i]['y']*400/$max);
$off2=$off+$gr;
$r=intval($gr/2);
echo "<area shape="circle" coords="".($off+$x).",".($off-$y).",".$r."" title="".$pianeti[$i]['nome']."`s ".$pianeti[$i]['nome_pianeta']."(".$pianeti[$i]['x'].",".$pianeti[$i]['y'].")"."" href="#" />";
}
echo "</map>";*/

}
else {
?>
<div style="text-align: center;">
	<div>
		<button onclick="$('#create').show();$('#search').hide()">[CREATE] [ALLY]</button>
		<button onclick="$('#search').show();$('#create').hide()">[SEARCH] [ALLY]</button>
	</div>
	<div id="create" style="display:none;">
		{table}
	</div>
	<div id="search" style="display:none;">
		<input type="search" id="inputsearch" placeholder="[SEARCH]" />
		<!-- <button>[SEARCH]</button> -->
		<p id="list"></p>
	</div>
</div>



<?php 
	$this->headScript()->captureStart();
	echo '$(function(){
		var cache = [];
		var key=[];
		$( "#inputsearch" ).autocomplete({
			minLength: 2,
			source: function( request, response ) {
				var term = request.term;
				var need=true;
				$.each(key,function(k,value){
					var v=new RegExp( $.ui.autocomplete.escapeRegex(value), "i" );
					need=need && !v.test(term);
				});
				if (need) {
					key.push(term);
					$.getJSON(path+"/alliance/search" , request, function( data, status, xhr ) {
						$.merge(cache,data);
						response(data);
					});
				}
				else response($.ui.autocomplete.filter(cache,term));
			},
			select:function(e,ui) {
				name=ui.item.label;
				id=ui.item.value;
				this.value=name;
				$("#list").html(\'<a href="'.$this->baseUrl('/alliance/show/name/').'\'+id+\'">\'+name+\'</a>\');
				return false;
			},
			focus:function(e,ui) {
				name=ui.item.label;
				this.value=name;
				return false;
			}
		});
	});';
	$this->headScript()->captureEnd();
	//echo '<center>al momento sei senza alleanza, puoi <a href="ally.php?action=cerca">cercarne</a> una o <a href="ally.php?action=crea">crearla</a></center>';


}
?>