<?php 
$this->log->debug(serialize(array('solar'=>100,'idro'=>90,'eolic'=>50,'pop'=>40,'ricerca'=>30)),'planet');

$this->headScript()->captureStart();
echo 'planet.data='.json_encode($this->planet->toArray()).';';
$this->headScript()->captureEnd();
?>

<div id="dialog"><form>
<?php 
echo $this->formSelect('galaxy',1,array('class'=>"ui-widget-content ui-corner-all"),Model_Planet::$galaxiy);
?>
	<input type="number" value="0" id="x" style="width: 50px;" min="-400" max="400" step="1" />
	|
	<input type="number" value="0" id="y" style="width: 50px;" min="-400" max="400" step="1" />

</form></div>

<table class="planet" border="1">
	<tr>
		<td>[NAME]</td>
		<td>[COORDS]</td>
		<td class="button"><button onclick="planet.add();" style="width:32px;height:32px" class="add">[ADD]</button></td>
	</tr>
	<?php 
	foreach ($this->planet as $key => $value) {
		echo '<tr>
		<td class="planet_name" id="p'.$key.'">'.$value['name']."</td>
		<td>".$this->planet->getGalaxy($key)." ".$value['x']." | ".$value['y'].'</td>
		<td class="button"><button style="width:32px;height:32px" class="edit" onclick="planet.edit('.$key.');">[EDIT]</button>
		<button style="width:32px;height:32px" onclick="planet.del('.$key.')" class="delete">[DELETE]</button></td></tr>';
	}
	?>
</table>

<div id="target" style="width: 300px;margin: 20px auto;padding: 5px;" class="ui-widget-content ui-corner-all">[TARGET] 
<?php 
echo $this->formSelect('galaxy',1,array('class'=>"ui-widget-content ui-corner-all"),Model_Planet::$galaxiy);
?>
	<input type="number" value="0" id="x" style="width: 50px;" min="-400" max="400" step="1" />
	|
	<input type="number" value="0" id="y" style="width: 50px;" min="-400" max="400" step="1" />
</div> 

<?php if ($this->planet->length>1) { ?>
<div style="text-align:center;">
	<span style="color: red;">Pi&ugrave; vicino</span> <span
		style="color: blue;">pi&ugrave; distante</span>
</div>

<table class="planet" border="1">
	<tr>
		<td></td>
		<?php 
		$distance=array();
		$max=0;
		foreach ($this->planet as $i=>$a) {
			foreach ($this->planet as $j=>$b) {
				$distance[$i][$j]=round(sqrt((($this->planet[$j]['x']-$this->planet[$i]['x'])*($this->planet[$j]['x']-$this->planet[$i]['x']))+(($this->planet[$j]['y']-$this->planet[$i]['y'])*($this->planet[$j]['y']-$this->planet[$i]['y']))),2);
				if ($distance[$i][$j]>$max) $max=$distance[$i][$j];
			}
		}
		foreach ($this->planet as $value) {
			echo "<td>".$value['name']."</td>";
		}
		?>
		<td>[TARGET]</td>
	</tr>
		<?php 
		if ($max!=0) $s=intval(255*4/$max); else $s=0;
		foreach ($this->planet as $i => $v) {
			echo "<tr><td>".$v['name']."</td>";
			foreach ($this->planet as $j => $b) {
				$c=1;
				$r=255;
				$v=0;
				$b=0;
				for ($k=0;$k<($distance[$i][$j]);$k++)
				{
					switch($c)
					{
						case "1" : $v+=$s;break;
						case "2" : $r-=$s;break;
						case "3" : $b+=$s;break;
						case "4" : $v-=$s;break;
						case "5" : $r+=$s;break;
						case "6" : $b-=$s;break;
					}
					if ($v>255) {
						$v=255;$c++;
					}
					if ($v<0) {
						$v=0;$c++;
					}
					if ($r>255) {
						$r=255;$c++;
					}
					if ($r<0) {
						$r=0;$c++;
					}
					if ($b>255) {
						$b=255;$c++;
					}
					if ($b<0) {
						$b=0;$c++;
					}
					if ($c>6) $c=1;
				}
				$re=dechex($r);
				$be=dechex($b);
				$ve=dechex($v);
				$ri=dechex(255-$r);
				$bi=dechex(255-$b);
				$vi=dechex(255-$v);
				if (strlen($re)<2) $re="0".$re;
				if (strlen($ve)<2) $ve="0".$ve;
				if (strlen($be)<2) $be="0".$be;
				if (strlen($ri)<2) $ri="0".$ri;
				if (strlen($vi)<2) $vi="0".$vi;
				if (strlen($bi)<2) $bi="0".$bi;
				$colore="#".$re.$ve.$be;
				$sfondo="";
				if (!$distance[$i][$j]) $sfondo="background: #".$ri.$vi.$bi.";";
				//$distance.="(".$pianeti[$j]['x'].",".$pianeti[$j]['y'].")(".$pianeti[$i]['x'].",".$pianeti[$i]['y'].")";
				if ($i!=$j) echo '<td style="color: '.$colore.'; '.$sfondo.'">'.$distance[$i][$j]."</td>"; else echo "<td>-</td>";
			}
			echo '<td id="d'.$i.'">'.round(sqrt(((0-$this->planet[$i]['x'])*(0-$this->planet[$i]['x']))+((0-$this->planet[$i]['y'])*(0-$this->planet[$i]['y']))),2).'</td></tr>';
		}
		?>
		</table>
<?php
}
/**
		 ?>

		mappa stellare dei pianeti<br />

		<a href="allY.php?action=mod">Modifica profilo</a><br />

		<a href="map.php?nome=".$_SESSION['nome']."&resize=1&g=1" rel="thumbnail" title="mappa">
		<img class="image" width="200" height="200" src="map.php?nome=".$_SESSION['nome']."&resize=1&g=1" title="G1" /></a>

		<a href="map.php?nome=".$_SESSION['nome']."&resize=1&g=2" rel="thumbnail" title="mappa">
		<img class="image" width="200" height="200" src="map.php?nome=".$_SESSION['nome']."&resize=1&g=2" title="G2" /></a>

		<a href="map.php?nome=".$_SESSION['nome']."&resize=1&g=3" rel="thumbnail" title="mappa">
		<img class="image" width="200" height="200" src="map.php?nome=".$_SESSION['nome']."&resize=1&g=3" title="G3" /></a>
		";

		$maxx=0;$maxy=0;$i=0;$minx=0;$miny=0;
		while($pianeti[$i])
		{
		$minx= $pianeti[$i]['x'] < $minx ? $pianeti[$i]['x'] : $minx ;
		$miny= $pianeti[$i]['y'] < $miny ? $pianeti[$i]['y'] : $miny ;
		$maxx= $pianeti[$i]['x'] > $maxx ? $pianeti[$i]['x'] : $maxx ;
		$maxy= $pianeti[$i]['y'] > $maxy ? $pianeti[$i]['y'] : $maxy ;
		$i++;
		}
		$max=$maxx > $maxy ? $maxx : $maxy;
		$min=$minx < $miny ? $minx : $miny;
		$min=0-$min;
		$max=$max > $min ? $max : $min ;
		$max++;
		$gr=intval(400/$max);
		echo "<map name="map" id="map">";
		for($i=0;$pianeti[$i];$i++)
		{
		$x=intval($pianeti[$i]['x']*400/$max);
		$off=intval(400);
		$y=intval($pianeti[$i]['y']*400/$max);
		$off2=$off+$gr;
		$r=intval($gr/2);
		echo "<area shape="circle" coords="".($off+$x).",".($off-$y).",".$r."" title="".$pianeti[$i]['nome_pianeta']."(".$pianeti[$i]['x'].",".$pianeti[$i]['y'].")"."" href="#" />";
		}
		echo "</map>";
		*/