<?php 
$this->key=array(
		''=>''
);

// visualizza truppe
?>
<!-- 
    show($tt,$navi,0,$razza);
    echo "
    <div align="center" id="forms" class="formular" style='display: none; color: black;'>

<form name="edit" action="ship.php?action=add" method="post">
  
    <table class="itable" cellpadding="2" cellspacing="1" width="350">

        <tr class="header1">
            <td colspan="4" class="header1">Inserisci truppe<a href="javascript:showforms('forms', 'formtext', 1)"><img align="right" src="images/close.gif" style="height:18px; width:18p;" /></a></td>
        </tr>
        <tr>
            <td class="zeile2"><label class="fieldLabel">Create in:</label></td>
            <td colspan="2" align="left" class="zeile2">";
    if ($pianeti) {
        echo"<select name="pianeta"><option value="">Seleziona</option>";
        $i=0;
        while($pianeti[$i])
        {
            echo "<option value="".$pianeti[$i]['pid']."">".$pianeti[$i]['nome_pianeta']."</option>";
            $i++;
        }    
        echo " </select>";
     }
     else echo "Nessun pianeta";
     echo "
            </td>
            <td class="zeile2" align="right">< !--
                <nobr>
            	X: <input class="ibox f30" type="text" name="x" id="x1" value="0" maxlength="4" size="4" />
                Y: <input class="ibox f30" type="text" name="y" id="y1" value="0" maxlength="4" size="4" />
                </nobr>-- >
            </td>
        </tr>
		<tbody id="unitAuto">
        <tr>
          <td class="zeile2">

          <label class="fieldLabel">Truppe	:</label><p></p><a href="javascript:switchtroops();" title="Inserisci Manualmente">Manuale</a>
          </td>
		  <td colspan="3" class="zeile2">
		  	<textarea onchange="autoins(this)" name="auto" class="ibox" style="width:250px; height:100px;"></textarea>
		  	<a href="javascript:void(0)" onmouseover="return overlib('Apri Imperion, e vai sulla base militare. Qui premi Ctrl+A e Ctrl+C. Dopo, torna in questo sito e premi Ctrl+V nel campo vuoto. Poi devi inserire le coordinate di dove hai creato le truppe e dove stanno ora. Le truppe verranno inserite automaticamente.');" onmouseout="return nd();">?</a>
		  </td>
		</tr>

		</tbody>
		<tbody id="unitManual" style='display: none'>
		<tr>
          <td class="zeile2" rowspan="12">
          <label class="fieldLabel">Navi	:</label><p></p><a href="javascript:switchtroops();" title="Inserisci Automaticamente">Auto</a>
          
          < !-- inserimento manuale -- >";
                   
        
	for ($i=1;$i<=12;$i++)
    {
        echo "<td width="20" class="zeile2"><img src="images/".$razza."/".$i.".gif" title="".$navi[$_SESSION['razza']][$i].""><td class="zeile2" width="170" align="left">".$navi[$_SESSION['razza']][$i].":</td><td class="zeile2" width="110" align="right"><input onkeyup="control(this)" class="ibox f80" type="text" size="9" name="t".$i."" value=""></td>\n";
        if ($i!="12") echo "</tr><tr>\n";
    }
    echo "
          </td>
        </tr>		
        </tbody>
		<tr>
        	<td colspan="4" class="footer"><input class="submit" type="submit" value="Salva" /></td>
        </tr>

    </table>
  </form>
</div>";
 
  -->