<!-- <img src="PATH/common/img/credits/" alt="" title=""> -->
<img src="PATH/common/img/credits/linux.png" alt="Linux" title="Linux">
<img src="PATH/common/img/credits/apache2.jpg" alt="Apache2" title="Apache2">
<img src="PATH/common/img/credits/mysql.gif" alt="Mysql" title="Mysql">
<img src="PATH/common/img/credits/php.png" alt="Php" title="Php">
<img src="PATH/common/img/credits/zf.png" alt="Zend Framework" title="Zend Framework">
<img src="PATH/common/img/credits/jquery.png" alt="jQuery" title="jQuery">

<p>[HOSTED] <a href="https://github.com/pagliaccio/login"><img alt="github" src="PATH/common/img/credits/github-mascotte.png"><img alt="github" src="PATH/common/img/credits/github.png"></a></p>