<?php 
//init

//var_dump($this->t->getLocale());

?>

<sumary style="text-align:center;"><h2><?php echo $this->t->_('CONTACT');?></h2>
<details>

<a href="mailto:toolraider@altervista.org"><?php echo $this->t->_('EMAIL_CONTACT');?></a>

<h3><?php echo $this->t->_('FORM_CONTACT');?></h3>
<div id="contact">
<form action="<?php echo $this->url(array('controller'=>"index",'action'=>'contact')); ?>" method="post" enctype="multipart/form-data">
<div>
<?php 
if ($this->auth->hasIdentity()) {
	echo $this->auth->getIdentity()->username;
} else {
    echo $this->t->_("LOGorEMAIL").' <a href="'.
    $this->url(array('controller'=>"login",'action'=>'index')).'">login</a>
    <input placeholder="email" name="email" required="required" type="email" size="40" />';
}
?></div>

<?php
$this->log->debug($this->auth->getIdentity());
$this->log->debug($this->auth->hasIdentity());
echo '
<div><input placeholder="'.$this->t->_("OBJECT").'" required="required" name="obj" size="40" maxlength="40" /></div>
<div>invia immagini delle schermate
<input type="file" name="upfile" /></div>
<textarea placeholder="'.$this->t->_("WRITE").'" name="text" required="required" cols="30" rows="10"></textarea>
<div><input type="submit" /></div>
';
?>
</form>
</div>
</details>
</sumary>