<?php 

if ($this->error) {
	$this->template()->Alert(print_r($this->text,true),$this->url(),2,5);
}
elseif ($this->success) {
	$this->template()->Alert(print_r($this->text,true),$this->url(),1,5);
}
else {
echo $this->t->_('RESEND');
?>
<form action="<?php echo $this->url(); ?>" method="post">
	<input type="email" size="10" name="email" value="<?php echo $this->email;?>" />
	<input type="submit" value="<?php echo $this->t->_('SEND');?>" />
</form>
<?php 
}
?>