<?php 
//init

$this->key=array(
		'RACE'=>$this->race,
		'NAME_PLANET'=>$this->ship['name'],
		'PID'=>intval($this->ship['pid']),
		'CLASS'=>($this->form ? 'ship' : 'readonly'),
//			''=>'',
//			'PLANET'=>'',
		'BASEURL'=>$this->baseUrl()
);
Zend_View_Filter_Tmpeng::addkey($this->key);
//$this->log->debug($this->ship,'in planetship');
?>
<div id="planetPID" style="padding:0;">
<table class="ship" style="margin: 10px auto;">
	<tr>
<?php 

if ($this->race=='ALIEN') $t=4;
else $t=12;
for ($i = 0; $i < $t; $i++) {
?>
    	<td><div class="ship RACE <?php echo str_replace(" ", "",$this->ship_name[$this->race][$i]);?>" title="<?php echo $this->ship_name[$this->race][$i];?>"></div></td>
<?php
}
?>
</tr><tr>
<?php
for ($j = 0; $j < $t; $j++) {
		$this->tot[$j]+=intval($this->ship['ships'][$j]);
?>
			<td><span id="t<?php echo $j;?>pPID" class="CLASS"><?php echo intval($this->ship['ships'][$j]);?></span>
				<form><input class="CLASS" type="number" id="i<?php echo $j;?>pPID" value="<?php echo intval($this->ship['ships'][$j]);?>" /></form></td>
<?php
	
}
?>
			<td>
<?php
if ($this->own) {
?>
				<button id="editPID" class="edit ship">[EDIT]</button>
<?php
}
if ($this->istot) {
	?>
	<button class="add" id="add_tab">[ADD]</button>
	<?php 
}
?>
			</td>
	</tr>
</table>		
</div>