<?php 
//init
$display=$this->own ? '[OWNSHIP]' : '[SHIPOF] '.$this->ship['username'];
$this->key=array(
			'SHIP_OF'=>$display,
			'RACE'=>$this->ship['race'],
			'ID_PLANET'=>intval($this->ship['pid']),
			'UID'=>$this->ship['uid'],
//			''=>'',
//			'PLANET'=>'',
			'BASEURL'=>$this->baseUrl()
		);
if (!$this->own) {
$this->headScript()->captureStart();
echo "
$(function(){
	$('.tot').hide().attr('aria-hidden','true').attr('aria-exspanded','false');
});
";
$this->headScript()->captureEnd();
}
//$this->log->debug($this->ship_name,'ship name');

/*
 * passare vettore al script a seconda di $this->own
 * 
 */
?>

<div id="dialog" title="Tab data">
    <form>
        <fieldset class="ui-helper-reset">
            <label for="tab_title">Title</label>
            <input type="text" name="tab_title" id="tab_title" value="" class="ui-widget-content ui-corner-all" />
            <label for="tab_content">Content</label>
            <textarea name="tab_content" id="tab_content" class="ui-widget-content ui-corner-all"></textarea>
        </fieldset>
    </form>
</div>
 
 
<div id="playerUID" class="tabs">
    <ul>
        <li><a href="#totUID">SHIP_OF</a></li>
        <?php 
$planet=new Zend_View();
$planet->tot=array();
$planet->race=$this->ship['race'];
$planet->log=$this->log;
$planet->own=$this->own;
$planet->ship_name=$this->ship_name;
$planet->addFilter('Tmpeng')->addFilterPath(APPLICATION_PATH.'/plugin');
$planet->setScriptPath(APPLICATION_PATH.'/views/scripts/template/');
$i=0;
$content="";
while ($this->ship[$i]) {
	$planet->ship=$this->ship[$i];
	$content.=$planet->render('planetship.phtml');
	echo '<li><a href="#planet'.$this->ship[$i]['pid'].'">'.$this->ship[$i]['name'].'</a> <span class="ui-icon ui-icon-close" style="display:inline-block;">Remove Tab</span></li>';
	$i++;
}

	
?>
    </ul>
    <div id="totUID" class="tot" >
<?php
$planet->ship=array('ships'=>$planet->tot);
$planet->own=false;
$planet->istot=true;
echo $planet->render('planetship.phtml');
?>  
    </div>
    <?php echo $content;?>
</div>