<?php 
//init
$display=$this->own ? '[OWNSHIP]' : '[SHIPOF] '.$this->ship['username'];
$this->key=array(
			'SHIP_OF'=>$display,
			'RACE'=>$this->ship['race'],
			'UID'=>$this->ship['uid'],
//			''=>'',
//			'PLANET'=>'',
			'BASEURL'=>$this->baseUrl()
		);
Zend_View_Filter_Tmpeng::addkey($this->key);
if (!$this->own) {
$this->headScript()->captureStart();
echo "
$(function(){
	$('.tot').hide().attr('aria-hidden','true').attr('aria-exspanded','false');
});
";
$this->headScript()->captureEnd();
}
//$this->log->debug($this->ship_name,'ship name');

/*
 * passare vettore al script a seconda di $this->own
 * 
 */

$list=array();
foreach ($this->list as $key=>$value) {
	if ($value) $list[$key]=$value['name'];
}
Zend_Registry::get('log')->debug($list,'list');
$planet=new Zend_View();
$planet->race=$this->ship['race'];
$planet->log=$this->log;
$planet->own=$this->own;
$planet->ship_name=$this->ship_name;
$planet->addFilter('Tmpeng')->addFilterPath(APPLICATION_PATH.'/plugin');
$planet->setScriptPath(APPLICATION_PATH.'/views/scripts/template/');

if ($this->own) {
?>

<div id="dialog" title="Tab data" style="width:800px;">
    <form>
        <fieldset class="ui-helper-reset">
            <label for="tab_title">[PLANET]</label>
            <?php 
            
            echo $this->formSelect('tab_title',1,array('class'=>"ui-widget-content ui-corner-all"),$list);
            
            ?>
            <label for="tab_content"></label>
            <div id="tab_content">
            <?php 
            $planet->form=true;
            echo $planet->render('planetship.phtml');
            ?>
            </div>
        </fieldset>
    </form>
</div>
<?php 
}
?>
 
<div id="playerUID" class="tabs">
    <ul>
        <li><a href="#totUID">SHIP_OF</a></li>
        <?php 

$planet->tot=array();
$planet->form=false;
$i=0;
$content="";
while ($this->ship[$i]) {
	$planet->ship=$this->ship[$i];
	$content.=$planet->render('planetship.phtml');
	echo '<li><a href="#planet'.$this->ship[$i]['pid'].'">'.$this->ship[$i]['name'].'</a> <span class="ui-icon ui-icon-close" style="display:inline-block;">Remove Tab</span></li>';
	$i++;
}

	
?>
    </ul>
    <div id="totUID" class="tot" style="padding:0;">
<?php
$planet->ship=array('ships'=>$planet->tot);
$planet->own=false;
$planet->istot=true;
echo $planet->render('planetship.phtml');
?>  
    </div>
    <?php echo $content;?>
</div>