<div id="dialog" title="[CONFIRM]">
[DELETE_CONFIRM]
<div>Password :<input id="delete" type="password" /></div>
</div>
<form class="profile">
<table style="width: 300px;">
  <tr id="username">
    <td>[USERNAME]</td>
    <td><span>NICK</span><input name="username" style="display:none;" required="required" value="NICK" /></td>
<?php 
if ($this->can) {
?>
    <td><button class="edit profile">[EDIT]</button></td>
<?php 
}
?>
  </tr>
  <tr id="email">
    <td>Email :</td>
    <td><span>EMAIL</span><input name="email" type="email" required="required" style="display:none;" value="EMAIL" /></td>
    <td><button class="edit profile">[EDIT]</button></td>
  </tr>
<?php 
foreach ($this->option as $key => $value) {
	if (!$value['label']) $value['label']=$value['value'];
	echo '<tr id="'.$key.'">
		<td>'.$value['name'].'</td>
		<td><span>'.$value['label'].'</span>';
	if (!$value['type']) $value['type']='Text';
	$value['attr']['style']='display:none;';
	if ($value['required']) $value['attr']['required']='required';
	$helper='form'.$value['type'];
	echo $this->$helper($key,$value['value'],$value['attr'],$value['option']);
	//$h=new Zend_View_Helper_FormSelect();$h->formSelect($name);
	//		<input '.(?'required="required"':'').' name="'.$key.'" style="display:none;" value="'.$value['value'].'" /></td>
	echo'<td><button class="edit profile">[EDIT]</button></td>
	</tr>';
}
?>
  <tr>
    <td class="button" colspan="3"><button>[CHANGEPASS]</button> <button>[DELETE] account</button></td>
  </tr>
  <tr class="password">
  	<td>[OLD_PASS] :</td>
  	<td colspan="2"><input name="password" type="password" /></td>
  </tr>
  <tr class="password">
  	<td><input id="password" name="new" type="password" /></td>
  	<td colspan="2"><input name="new2" type="password" /></td>
  </tr>
</table>
</form>