<?php 
//init
$auth=Zend_Auth::getInstance();
$ua=new Zend_Http_UserAgent();
$config = Zend_Registry::get('config');
$news="";
if ($config->local) $news='<li>le news not work on local</li>';
else{
	try {
		$feed =Zend_Feed::import('http://blogpagliaccio.wordpress.com/category/progetti/toolraider/feed/');
		$news="";
		// Loop over each channel item and store relevant data
		foreach ($feed as $item) {
			$date=new DateTime($item->pubDate());
			$news.='<li><span>'.$date->format("d/m/Y").'</span> <a href="'.$item->link().'">'.$item->title().'</a></li>';
		}
	} 
	catch (Zend_Feed_Exception $e) {
		$news="<li>$e</li>";
	}
}
?><!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="DESCRIPTION" content="<?php echo $this->t->_('DESCRIPTION');?>" />
		<meta name="KEYWORDS" content="imperion tools raid" />
		<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/favicon.ico" /><?php
	try {
		$device=$ua->getDevice();
		$mobile=$device->getFeature('is_mobile');
	} catch (Zend_Http_UserAgent_Exception $e) {
		$mobile=true;
	}
	echo $this->headLink()->prependStylesheet($this->baseUrl() . '/common/css/css.php'.($mobile? '?l=m' : ''));
	echo $this->headScript()->prependFile($this->baseUrl('/common/js/js.php'));
	if ($this->t->getLocale()!='en') echo '<script tipe="text/javascript" src="'.$this->baseURL('/common/js/localization/messages_'.$this->t->getLocale().'.js').'"></script>';
	echo '<script tipe="text/javascript">
	<!--
	var path="'.$this->baseUrl().'";
	//-->
	</script>';
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle($config->site);
	echo $this->headTitle();
?>
	</head>
	<body>
		<div id="loader" style="display:none;"><div></div></div>
		<div id="header"><h1>Toolraider</h1>
		<ul id="news">
			<li><span>Toolraider</span><a href="http://blogpagliaccio.wordpress.com/category/progetti/toolraider/">News</a></li>
			<?php echo $news;?>
		</ul>
		</div>
		<div id="locale">language 
			<form action="<?php echo $this->url();?>">
				<?php 
			$list=array_merge(array('browser'=>'auto'),$this->t->getList());
			echo $this->formSelect('locale',$_COOKIE['locale'],array('onchange'=>'submit();','id'=>'loc'),$list);
			?>
			</form>
		</div>
		<div id="container">
	<?php 
	if ($this->logger) {
		$text="<ol>";
		foreach ($this->logger as $value) {
			$text.='<li class="priority'.$value['priority'].'"><b>'.$value['info'].'</b> : '.$value['timestamp'].' - '.$value['message'].' - '.$value['priorityName']."</li>";
		}
		$text.="</ol>";
		echo $this->template()->spoiler($text,false,'log');
	}
	$page=array(
			array('label'=>'Home'
				,'module'=>'default'
				,'controller' => 'index'
				,'action'=>'index'
				,'order'=>0
			)
			,array('label'=>'Login'
				,'module'=>'default'
				,'controller' => 'login'
				,'action'=>'index'
				,'order'=>1
				,'resource'=>'login'
				,'privilege'=>'index'
			)
			,array('label'=>'Logout'
				,'module'=>'default'
				,'controller' => 'login'
				,'action'=>'logout'
				,'order'=>2
				,'resource'=>'login'
				,'privilege'=>'logout'
			)
			,array('label'=>'[REG]'
				,'module'=>'default'
				,'controller' => 'reg'
				,'action'=>'index'
				,'order'=>3
				,'resource'=>'reg'
				,'privilege'=>'index'
			)
			,array('label'=>'Shiptool'
					,'module'=>'default'
					,'controller' => 'shiptool'
					,'action'=>'index'
					,'order'=>4
					,'resource'=>'shiptool'
			)
			,array('label'=>'[PLANET_PANNEL]'
					,'module'=>'default'
					,'controller' => 'planet'
					,'action'=>'index'
					,'order'=>5
					,'resource'=>'planet'
			)
			,array('label'=>'Credits'
				,'module'=>'default'
				,'controller' => 'index'
				,'action'=>'credits'
				,'order'=>100
			)
		);
		$menu=new Zend_Navigation($page);
		$acl = Zend_Registry::get("acl");
		
		$this->navigation($menu)->setAcl($acl)->setRole(Model_Role::getRole());
		echo $this->navigation();//->menu();
			echo $this->layout()->content; ?>
		</div>
		<div id="footer">RINGRAZIAMENTI: a <b><a href="http://matt93.altervista.org" target="_blanc">matt93</a></b>, all'alleanza J.D. di imperion server 1 primo round e a DarckSimon per l'aiuto fornito <!--
<b><u><a href="http://www.traviantrucchi.org" target="_blanc">TravianTrucchi</a></b></u>
-->.<br />Le immagini sono concesse dalla TravianGames, proprietaria di tutti i diritti relativi ai contenuti. Questo sito non &egrave; gestito dalla TravianGames, e non &egrave; realizzato per scopi di lucro.
		</div>
	</body>
</html>